version: "3"

services: 
    webapp:
        build: ./webapp
        container_name: webapp
        ports:
            - "3000:3000"
    backend:
        build: ./backend
        container_name: backend
        ports: 
            - "4000:4000"